### ISSUE TITLE
Format of the annotation file

### ISSUE THREAD

**Issue by eduardcasas** [compbiolabucf/APA-Scan#2]
Hi,

the description of the format of the annotation file is not very clear, it just says it should be a .txt file, but with which fields (columns) and information? A regular .gtf file (the most widely used format for gene annotation is not supported? A little bit more information is required to find out how to parse from one format to another.

Thanks,

Eduard

**Comment by fnaima** [comment]
Thank you for your comment. The .txt annotation is downloaded from UCSC genome browser -> Table browser -> Group: Genes and Gene predictions, and with 'All fields from selected table'. I am attaching one image of the expected annotation file format in the user manual.
