### ISSUE TITLE
The `pileup' command has been removed. Please use `mpileup' instead`.

### ISSUE THREAD

**Issue by sopenaml** [compbiolabucf/APA-Scan#4]
When trying to run `APA-Scan` I get this  message: `[main] The `pileup' command has been removed. Please use `mpileup' instead`.  and the txt files per chr are all empty. In the script, there's a comment saying to use `pileup` not `mpileup`, but `pileup` is deprecated. Can you please indicate what to do? Shall we edit preprocess.py to call mpileup instead? Thank you very much

**Comment by naimafahmi** [comment]
Hello, the required version of samtools (0.1.8) is also provided in the directory. Please use that specific version, we need to use 'pileup' command here, 'mpileup' wont work.
The preprocess.py file should call samtools0.1.8 [if it is kept in the same directory]. You can also provide the absolute path of the samtools0.1.8 [editing the preprocess.py file]

**Comment by sopenaml** [comment]
Hello, I've downloaded the samtools file from the github and placed them on the same directory as the other python scripts. I then, tried to run it with no success. as I get: `sh: samtools: command not found`. I've noticed that the preprocess.py script has been updated recently, can you please explain/advice on the change, as the preprocess script I have is the previos version. Thank you very much.

Kind regards,

Miriam
________________________________

**Comment by naimafahmi** [comment]
I just updated these two lines by adding a  "./" before samtools, so that you could find samtools in your directory.
**cmd2_ = "./samtools view ........"
cmd3 = "./samtools pileup ........"**
You can also add the absolute path of where you kept the samtools.

**Comment by caylieshull** [comment]
@sopenaml I'm having the same issue getting `sh: samtools: command not found`.  Were you able to successfully solve this?

**Comment by naimafahmi** [comment]
Hi caylieshull,
Did you put the samtools (the one I have provided with the codes) in your current working directory?

**Comment by caylieshull** [comment]
@naimafahmi  Yes I did, and it still doesn't seem to be able to find it.  when I try ./samtools from the very same directory samtools runs fine, but when running the APA-Scan code from within that identical directory, I get the error.

**Comment by naimafahmi** [comment]
It is very strange! I downloaded the same folder again and it worked for me perfectly.
Okay, I just modified a little bit of code for you, can you please re-download the whole folder and run again? 
Also make sure you put the whole directory address for input/output dirs in the configuration.ini file.

**Comment by caylieshull** [comment]
My whole directory addresses are in the config file for input/output.  With your modified code I am getting the error sh: ./samtools: No such file or directory

To confirm that I've done this correctly, I have downloaded samtools v0.1.8 and it is in a directory called "samtools" within the folder where I am running APA-Scan.py from.  I have compiled samtools within the folder.  I have also tried running APA-Scan.py from within the samtools folder itself with no change.

**Comment by naimafahmi** [comment]
Did you download the preprocess.py file again? There is no "./samtools" command anymore, I changed that line. Can you please double check?
This is the one and only directory after downloading, which contains the code and samtools together:
![s](https://user-images.githubusercontent.com/47537266/140195191-378a239e-c1f5-4e12-ade7-326a1fb60e43.JPG)
